server:
  port: 8080
spring:
  application:
    name: java-test-assignment
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/tweetsDB
    username: matovic
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings=false:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false